version: 2
jobs:
 build:
 working_directory: ~/code
 docker:
 - image: circleci/android:api-30
 #- image: circleci/openjdk:8-jdk
 environment:
 JVM_OPTS: -Xmx3200m
 # TERM: dumb
 #machine:
 #environment:
 #- sudo ANDROID_HOME=/usr/local/android-sdk-linux ./gradlew dependencies
 steps:
 - checkout
 - restore_cache:
 key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
 #- run: ls
 - run:
 name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
 command: chmod +x ./gradlew
 #- run: ./gradlew dependencies
 #- run:
 # name: Run build
 # command: export TERM=${TERM:-dumb} && ./gradlew clean build # term not set
 - run: export TERM=xterm && ./gradlew androidDepedencies
 - run:
 name: Download Dependencies
 command: ./gradlew androidDependencies
 #- run: export TERM=xterm
 #- run: echo 'export TERM=xterm' >> $BASH_ENV
 - save_cache:
 paths:
 - ~/.gradle
 key: jars-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
 - run:
 name: Run Tests
 command: ./gradlew lint test
 - store_artifacts:
 path: app/build/reports
 destination: reports
 - store_test_results:
 path: app/build/test-results
